### ISSUE TITLE
SoundEffectInstance sometimes get exception.

### ISSUE THREAD

**Issue by yww325** [daxnet/typing-game#1]
I have seen access violation exception several times and null reference exception once.
-		$exception	{"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."}	System.AccessViolationException

StackTrace:
   at SharpDX.XAudio2.SourceVoice.GetState(Int32 flags)
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.PlatformGetState()
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.get_State()
   at Microsoft.Xna.Framework.Audio.SoundEffectInstancePool.Update()
   at Microsoft.Xna.Framework.FrameworkDispatcher.Update()
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at MonoGame.Framework.WinFormsGameWindow.TickOnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at MonoGame.Framework.WinFormsGameWindow.RunLoop()
   at MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at TypingGame.Program.Main() in D:\yww\GitHub\typing-game\src\Program.cs:line 18

**Comment by daxnet** [comment]
@yww325 
I have fixed this issue, please pull latest from master.
The fix was not so elegant, I simply used the lock mechanism to prevent the SoundEffect class from disposing on a changed object. Will figure out a better solution to such problem.
Thanks.
